/**
 * You are given two strings s and t.
 * 
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * 
 * Return the letter that was added to t.
 */
package Problems;

public class FindTheDifference {
    public static char findTheDifference(String s, String t) {
        int charNum = t.charAt(t.length() - 1);
        for (int i = 0; i < s.length(); i++) {
            charNum -= s.charAt(i);
            charNum += t.charAt(i);
        }

        return (char) charNum;
    }

    // another solution using bit manipulation
    public static char anotherFindTheDifference(String s, String t) {
        char res = t.charAt(t.length() - 1);
        for (int i = 0; i < t.length() - 1; ++i) {
            res ^= s.charAt(i);
            res ^= t.charAt(i);
        }

        return res;
    }

    public static void main(String[] args) {
        String s = "abcd";
        String t = "abcde";
        System.out.println(findTheDifference(s, t));
        System.out.println(anotherFindTheDifference(s, t));
    }
}
